# 文件作用：作为管理端服务的公共 facade。
# 关联说明：聚合 jobs、meta、qa_query、qa_write 等管理端服务给 routers/admin_v1 使用。

"""Public facade for admin QA, metadata, and job services."""

from .jobs import (
    ADMIN_JOB_STORE,
    AdminJob,
    AdminJobStore,
    cancel_job,
    complete_job,
    create_job,
    delete_job,
    fail_job,
    get_job,
    list_jobs,
    set_task,
    start_job,
    update_job,
)
from .meta import (
    ADMIN_META_STORE,
    AdminMeta,
    AdminMetaStore,
    batch_upsert,
    count_ids,
    delete_meta,
    get_meta_map,
    get_or_default,
    init_db,
    list_ids,
    upsert_meta,
)
from .qa import (
    AdminMilvusError,
    batch_update_fields,
    export_items_to_json,
    fetch_records_by_ids,
    get_qa_item,
    hard_delete,
    list_qa_items,
    replace_records,
    update_qa_item_fields,
)

__all__ = [
    "ADMIN_JOB_STORE",
    "ADMIN_META_STORE",
    "AdminJob",
    "AdminJobStore",
    "AdminMeta",
    "AdminMetaStore",
    "AdminMilvusError",
    "batch_update_fields",
    "batch_upsert",
    "cancel_job",
    "complete_job",
    "count_ids",
    "create_job",
    "delete_job",
    "delete_meta",
    "export_items_to_json",
    "fail_job",
    "fetch_records_by_ids",
    "get_job",
    "get_meta_map",
    "get_or_default",
    "get_qa_item",
    "hard_delete",
    "init_db",
    "list_ids",
    "list_jobs",
    "list_qa_items",
    "replace_records",
    "set_task",
    "start_job",
    "update_job",
    "update_qa_item_fields",
    "upsert_meta",
]
